// Package docker implements the Docker adapter for the AgentSpec toolchain.
package docker

import (
	"fmt"
	"strings"

	"github.com/szaher/designs/agentz/internal/ir"
)

// GenerateDockerfile creates a Dockerfile for the agent runtime.
func GenerateDockerfile(resources []ir.Resource, port int) string {
	var sb strings.Builder

	sb.WriteString("# Generated by agentspec - do not edit\n")
	sb.WriteString("FROM golang:1.25-alpine AS builder\n")
	sb.WriteString("WORKDIR /build\n")
	sb.WriteString("COPY go.mod go.sum ./\n")
	sb.WriteString("RUN go mod download\n")
	sb.WriteString("COPY . .\n")
	sb.WriteString("RUN go build -o /agentspec ./cmd/agentspec\n\n")

	sb.WriteString("FROM gcr.io/distroless/static-debian12\n")
	sb.WriteString("COPY --from=builder /agentspec /agentspec\n")
	sb.WriteString("COPY runtime-config.json /app/runtime-config.json\n")

	fmt.Fprintf(&sb, "EXPOSE %d\n", port)
	sb.WriteString("HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \\\n")
	fmt.Fprintf(&sb, "  CMD [\"/agentspec\", \"healthcheck\", \"--port\", \"%d\"]\n", port)
	fmt.Fprintf(&sb, "ENTRYPOINT [\"/agentspec\", \"serve\", \"--port\", \"%d\", \"--config\", \"/app/runtime-config.json\"]\n", port)

	return sb.String()
}

// agentPort extracts the port from deploy target config or returns the default.
func agentPort(resources []ir.Resource) int {
	for _, r := range resources {
		if r.Kind == "DeployTarget" {
			if p, ok := r.Attributes["port"]; ok {
				if port, ok := p.(float64); ok {
					return int(port)
				}
			}
		}
	}
	return 8080
}
