// Package compose implements the Docker Compose adapter for the AgentSpec toolchain.
package compose

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/szaher/designs/agentz/internal/adapters"
	"github.com/szaher/designs/agentz/internal/ir"
	"github.com/szaher/designs/agentz/internal/state"
)

func init() {
	adapters.Register("docker-compose", func() adapters.Adapter {
		return &Adapter{}
	})
}

// Adapter implements the docker-compose adapter.
type Adapter struct{}

// Name returns the adapter identifier.
func (a *Adapter) Name() string { return "docker-compose" }

// Validate checks whether resources are compatible with Docker Compose.
func (a *Adapter) Validate(_ context.Context, resources []ir.Resource) error {
	return nil
}

// Plan computes changes needed.
func (a *Adapter) Plan(_ context.Context, desired []ir.Resource, current []state.Entry) ([]adapters.Action, error) {
	return nil, nil
}

// Apply executes the planned actions.
func (a *Adapter) Apply(_ context.Context, actions []adapters.Action) ([]adapters.Result, error) {
	var results []adapters.Result
	for _, action := range actions {
		results = append(results, adapters.Result{
			FQN:    action.FQN,
			Action: action.Type,
			Status: adapters.ResultSuccess,
		})
	}
	return results, nil
}

// Export generates Docker Compose configuration files.
func (a *Adapter) Export(_ context.Context, resources []ir.Resource, outDir string) error {
	if err := os.MkdirAll(filepath.Join(outDir, "config"), 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Generated by agentspec - do not edit\n")
	sb.WriteString("version: \"3.8\"\n\n")
	sb.WriteString("services:\n")

	// Collect environment variables for .env file
	envVars := make(map[string]string)

	for _, r := range resources {
		switch r.Kind {
		case "Agent":
			name := sanitizeName(r.Name)
			fmt.Fprintf(&sb, "  %s:\n", name)
			fmt.Fprintf(&sb, "    container_name: %s\n", name)
			if model, ok := r.Attributes["model"].(string); ok {
				sb.WriteString("    environment:\n")
				fmt.Fprintf(&sb, "      - MODEL=%s\n", model)
				envVars["MODEL"] = model
			}
			sb.WriteString("    volumes:\n")
			fmt.Fprintf(&sb, "      - ./config/%s:/app/config:ro\n", name)
			sb.WriteString("\n")

		case "MCPServer":
			name := sanitizeName(r.Name)
			fmt.Fprintf(&sb, "  %s:\n", name)
			fmt.Fprintf(&sb, "    container_name: %s\n", name)
			if cmd, ok := r.Attributes["command"].(string); ok {
				fmt.Fprintf(&sb, "    command: %s\n", cmd)
			}
			if transport, ok := r.Attributes["transport"].(string); ok {
				if transport == "sse" || transport == "streamable-http" {
					sb.WriteString("    ports:\n")
					sb.WriteString("      - \"8080:8080\"\n")
				}
			}
			sb.WriteString("    volumes:\n")
			fmt.Fprintf(&sb, "      - ./config/%s:/app/config:ro\n", name)
			sb.WriteString("\n")
		}
	}

	// Write docker-compose.yml
	if err := os.WriteFile(filepath.Join(outDir, "docker-compose.yml"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	// Write .env file
	if len(envVars) > 0 {
		var envSB strings.Builder
		envSB.WriteString("# Generated by agentspec - do not edit\n")
		keys := make([]string, 0, len(envVars))
		for k := range envVars {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&envSB, "%s=%s\n", k, envVars[k])
		}
		if err := os.WriteFile(filepath.Join(outDir, ".env"), []byte(envSB.String()), 0644); err != nil {
			return err
		}
	}

	return nil
}

func sanitizeName(name string) string {
	return strings.ReplaceAll(name, " ", "-")
}
