package compiler

// mainTemplate is the Go source template for the compiled agent binary.
// It uses go:embed to load the runtime config JSON and starts an HTTP
// server with auth middleware, health endpoint, and agent routes.
const mainTemplate = `// Code generated by agentspec compile. DO NOT EDIT.
package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/szaher/designs/agentz/internal/auth"
	"github.com/szaher/designs/agentz/internal/runtime"
)

//go:embed config.json
var configJSON []byte

var (
	buildVersion = "{{.Version}}"
	buildTime    = "{{.BuildTime}}"
	buildTarget  = "{{.Target}}"
)

func main() {
	// Parse flags
	port := envInt("AGENTSPEC_PORT", flagInt("--port", 8080))
	host := envStr("AGENTSPEC_HOST", flagStr("--host", "0.0.0.0"))
	noAuth := envBool("AGENTSPEC_NO_AUTH", flagBool("--no-auth", false))
	logLevel := envStr("AGENTSPEC_LOG_LEVEL", flagStr("--log-level", "info"))
	logFormat := flagStr("--log-format", "text")
	configFile := flagStr("--config", "")
	showUI := flagBool("--ui", true)

	// Setup logger
	logger := setupLogger(logLevel, logFormat)

	// Load runtime config from embedded JSON
	var config runtime.RuntimeConfig
	if err := json.Unmarshal(configJSON, &config); err != nil {
		logger.Error("failed to parse embedded config", "error", err)
		os.Exit(1)
	}

	// Resolve config params for each agent
	resolver, err := runtime.NewConfigResolver(configFile)
	if err != nil {
		logger.Error("failed to initialize config resolver", "error", err)
		os.Exit(1)
	}

	for i, agent := range config.Agents {
		if len(agent.ConfigParams) > 0 {
			resolved, err := resolver.Resolve(agent.Name, agent.ConfigParams)
			if err != nil {
				logger.Error("config resolution failed", "agent", agent.Name, "error", err)
				os.Exit(1)
			}
			logger.Info("config resolved", "agent", agent.Name, "params", len(resolved.Values))
			_ = resolved // config values available via resolver at runtime
		}
		_ = i
	}

	// Get API key
	apiKey := auth.KeyFromEnv()

	// Create runtime
	rt, err := runtime.New(&config, runtime.Options{
		Port:   port,
		APIKey: apiKey,
		Logger: logger,
	})
	if err != nil {
		logger.Error("failed to create runtime", "error", err)
		os.Exit(1)
	}

	// Health check status
	logger.Info("starting compiled agent",
		"version", buildVersion,
		"agents", len(config.Agents),
		"port", port,
		"auth", !noAuth,
		"ui", showUI,
	)

	// Graceful shutdown
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	go func() {
		if err := rt.Start(ctx); err != nil && err != http.ErrServerClosed {
			logger.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	<-ctx.Done()
	logger.Info("shutting down...")

	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()

	if err := rt.Shutdown(shutdownCtx); err != nil {
		logger.Error("shutdown error", "error", err)
	}

	_ = host
	_ = noAuth
	_ = showUI
}

func setupLogger(level, format string) *slog.Logger {
	var lvl slog.Level
	switch strings.ToLower(level) {
	case "debug":
		lvl = slog.LevelDebug
	case "warn":
		lvl = slog.LevelWarn
	case "error":
		lvl = slog.LevelError
	default:
		lvl = slog.LevelInfo
	}

	opts := &slog.HandlerOptions{Level: lvl}
	var handler slog.Handler
	if format == "json" {
		handler = slog.NewJSONHandler(os.Stderr, opts)
	} else {
		handler = slog.NewTextHandler(os.Stderr, opts)
	}
	return slog.New(handler)
}

func flagStr(name, defaultVal string) string {
	for i, arg := range os.Args[1:] {
		if arg == name && i+1 < len(os.Args)-1 {
			return os.Args[i+2]
		}
		if strings.HasPrefix(arg, name+"=") {
			return strings.TrimPrefix(arg, name+"=")
		}
	}
	return defaultVal
}

func flagInt(name string, defaultVal int) int {
	s := flagStr(name, "")
	if s == "" {
		return defaultVal
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return defaultVal
	}
	return n
}

func flagBool(name string, defaultVal bool) bool {
	for _, arg := range os.Args[1:] {
		if arg == name {
			return true
		}
		if strings.HasPrefix(arg, name+"=") {
			val := strings.TrimPrefix(arg, name+"=")
			b, err := strconv.ParseBool(val)
			if err != nil {
				return defaultVal
			}
			return b
		}
	}
	return defaultVal
}

func envStr(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}

func envInt(key string, fallback int) int {
	if v, ok := os.LookupEnv(key); ok {
		n, err := strconv.Atoi(v)
		if err == nil {
			return n
		}
	}
	return fallback
}

func envBool(key string, fallback bool) bool {
	if v, ok := os.LookupEnv(key); ok {
		b, err := strconv.ParseBool(v)
		if err == nil {
			return b
		}
	}
	return fallback
}

// Ensure fmt is used.
var _ = fmt.Sprintf
`

// TemplateData holds the values to substitute into the main template.
type TemplateData struct {
	Version   string
	BuildTime string
	Target    string
}
