version: "2"
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
linters-settings:
  errcheck:
    check-type-assertions: true
formatters:
  enable:
    - gofmt
    - goimports
